### ISSUE TITLE
Add constraints length optimisation

### ISSUE THREAD

**Issue by elim0322** [cennznet/cennznut-rs#13]
Since we are using a bit as a flag for constraints presence (`has_constraints`), there isn't a case when there are 0 constraints (if `has_constraints`) -> constraints_length can be decremented by 1 when encoding & incremented by 1 when decoding to further optimise

**Comment by wilfred-centrality** [comment]
There is a defect related to this that did exist in `cennznut.js` where, if the max constraint length is defined as `257`, you will get undefined behaviour if that limit is met. This is because the number 257 does not fit within a byte.

**Comment by elim0322** [comment]
> There is a defect related to this that did exist in `cennznut.js` where, if the max constraint length is defined as `257`, you will get undefined behaviour if that limit is met. This is because the number `257` does not fit within a byte.

That's good to know thanks :)
