### ISSUE TITLE
Add helper functions to create Module and Method structs

### ISSUE THREAD

**Issue by elim0322** [cennznet/cennznut-rs#21]
The following structs are repeatedly created inside test functions:
- `Method`
- `Module`
- `CENNZnutV0`
- `Contract`

We want to write some helper function to create these structs and tidy up our tests.

Code pointer: how the structs are created for tests eg, https://github.com/cennznet/cennznut-rs/blob/master/src/test.rs#L14-L31

**Comment by HuanDay** [comment]
Would like working on this

**Comment by holygits** [comment]
closed via #23
